name: Build  Bot
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
      - main
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    # runs-on: ubuntu-latest
    # Use a container with GLIBC 2.17
    # container: quay.io/pypa/manylinux2014_x86_64
    timeout-minutes: 30
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show GLIBC
        run: ldd --version
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build
        run: sh script/build.sh
      - name: PokeBall Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot
          path: bot
          retention-days: 1

  build_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: copy artifact
        run: |
          cp bot/bot build/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: build
          push: true
          tags: taropowder/lyl_chat_bot:latest
